services:
  backend:
    build:
      context: ./nodejs-backend
    container_name: nodejs-srv
    ports:
      - '5500:5500'
    volumes:
      - ./nodejs-backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      EMAIL_HOST: mailhog
      EMAIL_PORT: 1025
      EMAIL_USER: test@example.com
      EMAIL_PASS: password
      PORT: 5500
      DATABASE_URL: postgresql://postgres:postgres@postgresql-srv:5432/app_db?schema=public
    command: ['npm', 'run', 'dev']
    depends_on:
      - postgresql
      - mailhog
    networks:
      - app-network

  frontend:
    build:
      context: ./react-frontend
    container_name: react-app
    ports:
      - '3000:3000'
    volumes:
      - ./react-frontend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
    command: ['npm', 'start']
    depends_on:
      - backend
    networks:
      - app-network

  postgresql:
    image: postgres:15
    container_name: postgresql-srv
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - app-network

  mailhog:
    image: mailhog/mailhog
    platform: linux/amd64
    container_name: mailhog
    ports:
      - '8025:8025' # MailHog UI
      - '1025:1025' # SMTP Port
    networks:
      - app-network
    depends_on:
      - postgresql

volumes:
  postgresql_data:

networks:
  app-network:
    driver: bridge
